---
slug: explore_flask
filename: explore_flask
title: Explore Flask
description: Patterns and best practices for building web apps with Flask
author: Robert Picard
copyright: 2014
uuid: b937c494-40e7-4522-8151-01d9fe676d03
